# targets:
#   $default:
#     builders:
#       source_gen|combining_builder:
#         options:
#           build_extensions:
#             '^lib/model/{{}}.dart': 'lib/model/_generated/{{}}.g.dart'
#       freezed:
#         options:
#           build_extensions:
#             '^lib/model/{{}}.dart': 'lib/model/_generated/{{}}.freezed.dart'